[BE] 방문 기록 기능 구현
Team-Minionz/springboot-study-project-qrna pull request #10
Opened 2021-10-02 12:35 UTC by jeongyuneo

2021-10-03 14:23 UTC, PandaHun requested changes
코멘트 남겼습니다 확인해주세요

2021-10-03 14:23 UTC, PandaHun commented on backend/src/main/java/com/minionz/backend/shop/domain/ShopRepository.java
> +    Shop findByTelNumber(String telNumber);
`telNumber`로 해당 `Shop`이 없다면?

2021-10-03 14:23 UTC, PandaHun commented on backend/src/main/java/com/minionz/backend/user/domain/UserRepository.java
> +    User findByEmail(String email);
`ShopRepository`와 마찬가지로 해당 `email`의 `User`가 없다면?

2021-10-03 14:23 UTC, PandaHun commented on backend/src/main/java/com/minionz/backend/visit/service/VisitService.java
> +        Shop shop = shopRepository.findByTelNumber(checkInRequestDto.getShopTelNumber());
위 두 값이 null-safe 할까?

2021-10-04 14:04 UTC, jeongyuneo commented on backend/src/main/java/com/minionz/backend/visit/service/VisitService.java
> +        Shop shop = shopRepository.findByTelNumber(checkInRequestDto.getShopTelNumber());
체크인 서비스는 로그인 시 해당 유저 정보 존재여부를 확인해서 null-safe하다고 생각해서 성능저하의 우려가 있는 Optional을 사용하지 않았는데, 성능저하가 되더라도 NPE을 방지하지하는게 더 바람직한 방법인가요?

2021-10-05 00:48 UTC, PandaHun commented on backend/src/main/java/com/minionz/backend/visit/service/VisitService.java
> +        Shop shop = shopRepository.findByTelNumber(checkInRequestDto.getShopTelNumber());
1. NPE가 나지 않는다는 것을, 전체 코드를 모르는 사람이 봐도 이해할 수 있을 까요?
2. 로그인이 된 시점에서, 다른 사용자가 해당 사용자 혹은 Shop의 정보를 변경하거나, 삭제했다면? NPE가 발생하지 않을까요?
3. 성능 저하의 우려는 어떠한 성능 저하를 말하는 걸까요?

2021-10-05 08:00 UTC, jeongyuneo commented on backend/src/main/java/com/minionz/backend/visit/service/VisitService.java
> +        Shop shop = shopRepository.findByTelNumber(checkInRequestDto.getShopTelNumber());
수정 완료

2021-10-05 08:00 UTC, jeongyuneo commented on backend/src/main/java/com/minionz/backend/shop/domain/ShopRepository.java
> +    Shop findByTelNumber(String telNumber);
수정 완료

2021-10-05 08:00 UTC, jeongyuneo commented on backend/src/main/java/com/minionz/backend/user/domain/UserRepository.java
> +    User findByEmail(String email);
수정 완료

2021-10-05 08:24 UTC, PandaHun approved these changes

2021-10-05 08:54 UTC, merged