[BE] 회원가입과 회원탈퇴 기능 구현
Team-Minionz/springboot-study-project-qrna pull request #11
Opened 2021-10-02 13:09 UTC by malpipapi

2021-10-03 12:35 UTC, Livenow14 commented
#8

2021-10-03 14:30 UTC, PandaHun requested changes
코멘트 남겼습니다 확인해주세요

2021-10-03 14:30 UTC, PandaHun commented on backend/src/main/java/com/minionz/backend/user/domain/UserRepository.java
> +    User findByEmail(String email);
해당 `email`의 `User`가 없다면?

2021-10-03 14:30 UTC, PandaHun commented on backend/src/main/java/com/minionz/backend/user/service/UserService.java
> +        User userOut = userJoinRequest.toEntity(userIn);
`userIn`, `userOut`이 과연 가입과 맞는 네이밍일까요?

2021-10-03 14:30 UTC, PandaHun commented on backend/src/main/java/com/minionz/backend/user/service/UserService.java
> +        User userIn = userRepository.findByEmail(userJoinRequest.getEmail());
null-safe 할까요?

2021-10-03 14:30 UTC, PandaHun commented on backend/src/main/java/com/minionz/backend/user/service/UserService.java
> +        User user = userRepository.findByEmail(email);
마찬가지로 null-safe 할까요?

2021-10-03 14:30 UTC, PandaHun commented on backend/src/main/java/com/minionz/backend/user/controller/dto/UserWithdrawResponse.java
>      private int statusCode;
`setter`?...

2021-10-06 14:21 UTC, malpipapi commented on backend/src/main/java/com/minionz/backend/user/domain/UserRepository.java
> +    User findByEmail(String email);
User가 무조건 email을 갖고있을거라 생각했습니다. 예외발생을 위해 Optional<User>로 다시 바꿨습니다. NPE 에 대한 예외발생을 더 생각하면서 Optional 에 대한 공부를 하겠습니다.

2021-10-06 14:23 UTC, malpipapi commented on backend/src/main/java/com/minionz/backend/user/service/UserService.java
> +        User userOut = userJoinRequest.toEntity(userIn);
가입과 맞는 네이밍이라고 생각하지 않습니다. 정신없이 구현하다보니 저렇게 한것 같습니다. 자바 컨벤션 규칙을 생각하면서 네이밍에 좀더 신경 써보도록 하겠습니다.

2021-10-06 14:25 UTC, malpipapi commented on backend/src/main/java/com/minionz/backend/user/service/UserService.java
> +        User user = userRepository.findByEmail(email);
null-safe하지 않다고 생각합니다. 객체가 비어있다고 가정하에 orElseThrow를 통해서 Supplier 함수형 인자를 통해 예외를 던져주도록 변경하겠습니다

2021-10-07 06:20 UTC, PandaHun requested changes

2021-10-07 06:20 UTC, PandaHun commented on backend/src/main/java/com/minionz/backend/user/controller/dto/UserWithdrawResponse.java
> +    private int statsCode;
이전 네이밍이 맞는 네이밍 같은데...?

2021-10-07 06:20 UTC, PandaHun commented on backend/src/main/java/com/minionz/backend/user/service/UserService.java
> +        return new UserJoinResponse(userRepository.save(user));
`save`를 두 번 수행하는 이유는?...

2021-10-07 08:26 UTC, malpipapi commented on backend/src/main/java/com/minionz/backend/user/service/UserService.java
> +        return new UserJoinResponse(userRepository.save(user));
save를 두번 수행해준건 제 실수입니다. return 에다 바로 save수행하게끔 만들어줬습니다.

2021-10-07 09:05 UTC, closed without merging